services:
  postgres:
    image: postgres
    container_name: finkalk_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

#   mongo:
#     image: mongo
#     container_name: mongo
#     restart: unless-stopped
#     env_file:
#       - .env
#     ports:
#       - "${MONGO_PORT}:27017"
#     volumes:
#       - ./docker/mongo/data:/data/db

  redis:
    image: redis
    container_name: finkalk_redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker/redis/data:/data
